apiVersion: apps/v1
kind: Deployment
metadata:
  name: imp-app
  namespace: grupoguma
  labels:
    app: importacion
spec:
  replicas: 3
  selector:
    matchLabels:
      app: imp-app
  template:
    metadata:
      labels:
        app: imp-app
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mysql-pvc
      imagePullSecrets:
        - name: regcred
      containers:
        - name: cn-imp-app
          image: gumadesarrollo/importacion:v1.1.{{BUILD_NUMBER}}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
          - configMapRef:
              name: laravel-config
          env:
            - name: APP_KEY
              value: base64:lXDDp5xzYk1avcHc1Jj+52OGX4hQM75buwc/bPlSjiI=
            - name: DB_DATABASE
              value: solicitud
          resources:
            requests:
              memory: "64Mi"
              cpu: "72m"
            limits:
              memory: "128Mi"
              cpu: "144m"
---
apiVersion: v1
kind: Service
metadata:
  name: imp-svc
  namespace: grupoguma
spec:
  selector:    
    app: imp-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80