version: "3.7"

services:  
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME:?err}-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - .:/var/www/html/public
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - app
      - mysql
    networks:
      - networkapp

  mysql:
    image: mysql:5.7
    container_name: ${APP_NAME:?err}-mysql
    restart: always
    environment:
      MYSQL_DATABASE: db_database
      MYSQL_USER: usr_container
      MYSQL_PASSWORD: pss_container
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
    ports:
      - 3306:3306
    volumes:
      - _vol:/var/lib/mysql
    networks:
      - networkapp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME:?err}-phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
      - 8081:80
    networks:
      - networkapp
  app:
    build: ./docker
    container_name: ${APP_NAME:?err}-php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - networkapp

networks: 
  networkapp:

volumes:
  _vol: