apiVersion: v1
kind: Service
metadata:  
  name: imp-svc 
  namespace: grupoguma
spec:
  selector:    
    app: imp-app
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30002
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10000